### PR TITLE
ksp 1.2.2 test changes by Jebs_SY

### PR DESCRIPTION
**Pull request by raidernick**
-changes to configs to fix various isssues introduced by ksp 1.2 for ksp 1.2.2
-fixes to chutes, reflections, part categories and landing modules
-changes by Jebs_SY

-preliminary changes do not merge yet

### CODE REVIEW

**Comment by stratochief66** [comment]
I've got this for testing myself now.

I just want to link the forum post that discusses the new requirements as well:
http://forum.kerbalspaceprogram.com/index.php?/topic/22888-105-fasa-544/&do=findComment&comment=2918003

**Comment by sharktails** [comment]
The lem is broke not letting kerbals get out it says the hatch is blocked and please sort out the legs its just not the same i cant programme and i am pleased there are programers out there working on stuff like this but having all the working part is a lot better and thank ou for taking the time to work on this mod

**Comment by raidernick** [comment]
@sharktails the lem requires RPM to work correctly and the legs work fine

**Comment by sharktails** [comment]
thank you @raidernick

**Comment by stratochief66** [comment]
There should be a better solution to the parachute issue, which I haven't personally run into. But because the chute changes here are commenting out, that can be fixed in the future just fine.

**Pull request merged**
